xcb-util: fix conflict with Poky's xcb-util-image
Adding the meta-qt5 layer and building the qtbase package the following
error occurred:

ERROR: qtbase-5.12.6+gitAUTOINC+f0b93f7a4b-r0 do_prepare_recipe_sysroot: The file /usr/include/xcb/xcb_bitops.h is installed by both xcb-util and xcb-util-image, aborting

Since the libxcb-image-dev package built from Poky's xcb-util-image recipe
contains xcb_bitops.h, remove it from the libxcb-util-dev package built
from the xcb-util recipe.

Steps to reproduce:

1. Clone meta-emlinux:
  $ mkdir repos
  $ git clone -b warrior https://github.com/miraclelinux/meta-emlinux.git repos/meta-emlinux
2. Clone meta-qt5:
  $ git clone -b warrior https://github.com/meta-qt5/meta-qt5 repos/meta-qt5
3. Setup build directory:
  $ source repos/meta-emlinux/scripts/setup-emlinux build
4. Add meta-qt5 layer to conf/bblayers.conf:
  $ bitbake-layers add-layer ../repos/meta-qt5
5. Set target machine to conf/local.conf:
  $ echo "MACHINE = \"qemuarm64\"" >> conf/local.conf
6. Setup mirror:
  $ cat <<'EOF' >> conf/local.conf
CTJ_DEBIAN_MIRROR='http://emlinux-pkgs.miraclelinux.com/debian/pool'
MIRRORS+="${DEBIAN_MIRROR}    ${CTJ_DEBIAN_MIRROR} \n"
EOF
7. Build qtbase package:
  $ bitbake qtbase